/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package booksh;

import javax.swing.JOptionPane;

/**
 *
 * @author shadman
 */
public class book_rect_view extends javax.swing.JPanel {

    /**
     * Creates new form book_rect_view
     * @param book
     */
    Book book;
    public book_rect_view(Book book) {
        initComponents();
        this.book = book;
        lb_bookname.setText(book.name);
        lb_author.setText(book.author+" ");
        lb_genre.setText(book.genre);
        lb_year.setText(String.valueOf(book.year));
        lb_rating.setText(String.valueOf(book.rating));
        lb_price.setText(String.valueOf(book.price));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_bookname = new javax.swing.JLabel();
        lb_author = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lb_genre = new javax.swing.JLabel();
        lb_year = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lb_rating = new javax.swing.JLabel();
        lb_price = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ic_boroow = new rojerusan.RSLabelImage();
        ic_buy = new rojerusan.RSLabelImage();
        ic_wishlist = new rojerusan.RSLabelImage();

        setBackground(new java.awt.Color(151, 151, 251));
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(251, 51, 51)));
        setForeground(new java.awt.Color(51, 51, 51));
        setFont(new java.awt.Font("Glass Antiqua", 0, 18)); // NOI18N
        setMinimumSize(new java.awt.Dimension(280, 400));
        setPreferredSize(new java.awt.Dimension(280, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_bookname.setFont(new java.awt.Font("Glass Antiqua", 1, 36)); // NOI18N
        lb_bookname.setForeground(new java.awt.Color(51, 51, 51));
        lb_bookname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_bookname.setText("Book Name");
        add(lb_bookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 230, 50));

        lb_author.setFont(new java.awt.Font("Glass Antiqua", 2, 24)); // NOI18N
        lb_author.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lb_author.setText("Author Name ");
        add(lb_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 210, 60));

        jLabel3.setFont(new java.awt.Font("Glass Antiqua", 0, 18)); // NOI18N
        jLabel3.setText("Genre");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 50, 30));

        lb_genre.setFont(new java.awt.Font("Glass Antiqua", 0, 18)); // NOI18N
        lb_genre.setText("Thriller");
        add(lb_genre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, 20));

        lb_year.setFont(new java.awt.Font("Glass Antiqua", 0, 18)); // NOI18N
        lb_year.setText("2017");
        add(lb_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, 20));

        jLabel5.setFont(new java.awt.Font("Glass Antiqua", 0, 18)); // NOI18N
        jLabel5.setText("Published");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 90, 30));

        lb_rating.setFont(new java.awt.Font("Glass Antiqua", 0, 18)); // NOI18N
        lb_rating.setText("4.2");
        add(lb_rating, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, 20));

        lb_price.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lb_price.setText("250");
        add(lb_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Price");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 50, 30));

        jLabel7.setFont(new java.awt.Font("Glass Antiqua", 0, 18)); // NOI18N
        jLabel7.setText("Rating");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 50, 30));

        ic_boroow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Sell_50px.png"))); // NOI18N
        ic_boroow.setToolTipText("Borrow");
        ic_boroow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ic_boroowMouseClicked(evt);
            }
        });
        add(ic_boroow, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 50, 40));

        ic_buy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-buy-50.png"))); // NOI18N
        ic_buy.setToolTipText("Buy");
        ic_buy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ic_buyMouseClicked(evt);
            }
        });
        add(ic_buy, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 50, 40));

        ic_wishlist.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ic_wishlist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-love-50.png"))); // NOI18N
        ic_wishlist.setToolTipText("Add to Wishlist");
        ic_wishlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ic_wishlistMouseClicked(evt);
            }
        });
        add(ic_wishlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 50, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void ic_boroowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ic_boroowMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, this.book.name + " asked to borrow");
    }//GEN-LAST:event_ic_boroowMouseClicked

    private void ic_buyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ic_buyMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, this.book.name + " added to cart");
    }//GEN-LAST:event_ic_buyMouseClicked

    private void ic_wishlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ic_wishlistMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, this.book.name + " added to wishlist");
    }//GEN-LAST:event_ic_wishlistMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSLabelImage ic_boroow;
    private rojerusan.RSLabelImage ic_buy;
    private rojerusan.RSLabelImage ic_wishlist;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lb_author;
    private javax.swing.JLabel lb_bookname;
    private javax.swing.JLabel lb_genre;
    private javax.swing.JLabel lb_price;
    private javax.swing.JLabel lb_rating;
    private javax.swing.JLabel lb_year;
    // End of variables declaration//GEN-END:variables
}
