/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package booksh;

import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shadman
 */
public class ManageBooksPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageBooksPanel
     */
    public ManageBooksPanel() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_bookid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_bookname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_bookauthor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_bookprice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_bookquantity = new javax.swing.JTextField();
        btn_remove = new rojerusan.RSMaterialButtonCircle();
        btn_add = new rojerusan.RSMaterialButtonCircle();
        btn_modify = new rojerusan.RSMaterialButtonCircle();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_booklist = new rojerusan.RSTableMetro();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Glass Antiqua", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ISBN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        txt_bookid.setBackground(new java.awt.Color(102, 102, 255));
        txt_bookid.setFont(new java.awt.Font("Glass Antiqua", 0, 18)); // NOI18N
        txt_bookid.setForeground(new java.awt.Color(255, 255, 255));
        txt_bookid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_bookid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bookidActionPerformed(evt);
            }
        });
        jPanel1.add(txt_bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 230, 30));

        jLabel2.setFont(new java.awt.Font("Glass Antiqua", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_26px.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Glass Antiqua", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Glass Antiqua", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_26px.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        txt_bookname.setBackground(new java.awt.Color(102, 102, 255));
        txt_bookname.setFont(new java.awt.Font("Glass Antiqua", 0, 18)); // NOI18N
        txt_bookname.setForeground(new java.awt.Color(255, 255, 255));
        txt_bookname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_bookname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_booknameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_bookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 230, 30));

        jLabel5.setFont(new java.awt.Font("Glass Antiqua", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Author");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        txt_bookauthor.setBackground(new java.awt.Color(102, 102, 255));
        txt_bookauthor.setFont(new java.awt.Font("Glass Antiqua", 0, 18)); // NOI18N
        txt_bookauthor.setForeground(new java.awt.Color(255, 255, 255));
        txt_bookauthor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_bookauthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bookauthorActionPerformed(evt);
            }
        });
        jPanel1.add(txt_bookauthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 230, 30));

        jLabel6.setFont(new java.awt.Font("Glass Antiqua", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_26px.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Glass Antiqua", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_26px.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        txt_bookprice.setBackground(new java.awt.Color(102, 102, 255));
        txt_bookprice.setFont(new java.awt.Font("Glass Antiqua", 0, 18)); // NOI18N
        txt_bookprice.setForeground(new java.awt.Color(255, 255, 255));
        txt_bookprice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_bookprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bookpriceActionPerformed(evt);
            }
        });
        jPanel1.add(txt_bookprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 230, 30));

        jLabel8.setFont(new java.awt.Font("Glass Antiqua", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Price");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel9.setFont(new java.awt.Font("Glass Antiqua", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Quantity");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        jLabel10.setFont(new java.awt.Font("Glass Antiqua", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_26px.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, -1));

        txt_bookquantity.setBackground(new java.awt.Color(102, 102, 255));
        txt_bookquantity.setFont(new java.awt.Font("Glass Antiqua", 0, 18)); // NOI18N
        txt_bookquantity.setForeground(new java.awt.Color(255, 255, 255));
        txt_bookquantity.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_bookquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bookquantityActionPerformed(evt);
            }
        });
        jPanel1.add(txt_bookquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 230, 30));

        btn_remove.setBackground(new java.awt.Color(250, 51, 51));
        btn_remove.setText("Remove");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 630, -1, 50));

        btn_add.setBackground(new java.awt.Color(250, 51, 51));
        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, -1, 50));

        btn_modify.setBackground(new java.awt.Color(250, 51, 51));
        btn_modify.setText("Modify");
        btn_modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifyActionPerformed(evt);
            }
        });
        jPanel1.add(btn_modify, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 630, -1, 50));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 370, 720));

        tbl_booklist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "ISBN", "Author", "Price", "Quantity"
            }
        ));
        tbl_booklist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_booklistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_booklist);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 640, 460));

        jLabel11.setFont(new java.awt.Font("Glass Antiqua", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(251, 51, 51));
        jLabel11.setText("Manage Books");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 160, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_bookidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bookidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bookidActionPerformed

    private void txt_booknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_booknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_booknameActionPerformed

    private void txt_bookauthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bookauthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bookauthorActionPerformed

    private void txt_bookpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bookpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bookpriceActionPerformed

    private void txt_bookquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bookquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bookquantityActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        String id = txt_bookid.getText();
        String name = txt_bookname.getText();
        String author = txt_bookauthor.getText();
        String quantity = txt_bookquantity.getText();
        String price = txt_bookprice.getText();
        if (name.equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter name");
            return;
        }

        if (id.equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter ISBN");
            return;
        }
        if (author.equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter Author");
            return;
        }
        if (quantity.equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter Quantity");
            return;
        }
        if (price.equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter Price");
            return;
        }
        DefaultTableModel tblModel = (DefaultTableModel) tbl_booklist.getModel();
        Vector<String> lst = new Vector<>();
        lst.add(name);
        lst.add(id);
        lst.add(author);
        lst.add(price);
        lst.add(quantity);
        tblModel.addRow(lst);
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_modifyActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_removeActionPerformed

    private void tbl_booklistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_booklistMouseClicked
        // TODO add your handling code here:
        int sec = tbl_booklist.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tbl_booklist.getModel();
        String name = (String)model.getValueAt(sec, 0);
        String id = (String)model.getValueAt(sec, 1);
        String author = (String)model.getValueAt(sec, 2);
        String price = (String)model.getValueAt(sec, 3);
        String quantity = (String)model.getValueAt(sec, 5);

        txt_bookname.setText(name);
        txt_bookid.setText(id);
        txt_bookauthor.setText(author);
        txt_bookprice.setText(price);
        txt_bookquantity.setText(quantity);
    }//GEN-LAST:event_tbl_booklistMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle btn_add;
    private rojerusan.RSMaterialButtonCircle btn_modify;
    private rojerusan.RSMaterialButtonCircle btn_remove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSTableMetro tbl_booklist;
    private javax.swing.JTextField txt_bookauthor;
    private javax.swing.JTextField txt_bookid;
    private javax.swing.JTextField txt_bookname;
    private javax.swing.JTextField txt_bookprice;
    private javax.swing.JTextField txt_bookquantity;
    // End of variables declaration//GEN-END:variables
}
