/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package booksh;

import lib.WrapLayout;
import java.awt.Rectangle;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import booksh.subpanels.OrderInfoPanel;
import booksh.subpanels.OrderInfoPanelBuy;

/**
 *
 * @author shadman
 */
public class Notification_view extends javax.swing.JPanel {

    /**
     * Creates new form BookView
     */
    ArrayList<Book> books;
    int rows = 0;
    static final Rectangle pnl = new Rectangle(1073, 62);

    public Notification_view() {
        initComponents();
        load_notifications();
    }

    public void load_notifications() {
        try {
            var con = DBConnection.getConnection();
            var rs = con.prepareStatement("SELECT COUNT(request_id) FROM requests").executeQuery();
            if (rs.next()) rows = rs.getInt(1);

            String query = "SELECT * FROM requests INNER JOIN book_details ON book_details.book_id = requests.book_id INNER JOIN users ON users.id = requests.user_id";
            this.setLayout(new WrapLayout(WrapLayout.LEADING, 80, 20));
            var grid = this;
            this.setBackground(Cl.bgp);

            var pat = con.prepareStatement(query);
            rs = pat.executeQuery();
            while (rs.next()) {
                int user_id = rs.getInt("user_id");
                int book_id = rs.getInt("book_id");
                String uname = rs.getString("users.name");
                String book = rs.getString("book_details.name");
                String author = rs.getString("book_details.author");
                String type = rs.getString("requests.type");
                if (type.equals("BRW")) {
                    var oderinfo = new OrderInfoPanel();
                    oderinfo.set_data(user_id, book_id, uname, book, author);
                    this.add(oderinfo);
                } else if (type.equals("BUY")) {
                    var oderinfo = new OrderInfoPanelBuy();
                    oderinfo.set_data(user_id, book_id, uname, book, author);
                    this.add(oderinfo);
                }
                this.invalidate();
                this.validate();
                this.repaint();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
