/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package booksh;

import javax.swing.JScrollBar;

/**
 *
 * @author shadman
 */
public class UserProfile extends javax.swing.JPanel {

    /**
     * Creates new form UserProfile
     */
    public UserProfile() {
        initComponents();
        JScrollBar verticalScrollBar = jScrollPane1.getVerticalScrollBar();
        verticalScrollBar.setUnitIncrement(20);
        verticalScrollBar.setBlockIncrement(200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        rSPanelCircleImage1 = new rojerusan.RSPanelCircleImage();
        rSLabelImage1 = new rojerusan.RSLabelImage();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        txt_bookcount = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        txt_bookcount2 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        txt_bookcount1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelRound1 = new lib.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        panelRound2 = new lib.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        panelRound3 = new lib.PanelRound();
        jLabel8 = new javax.swing.JLabel();
        panelRound4 = new lib.PanelRound();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelRound5 = new lib.PanelRound();
        jLabel11 = new javax.swing.JLabel();
        panelRound6 = new lib.PanelRound();
        jLabel12 = new javax.swing.JLabel();
        panelRound7 = new lib.PanelRound();
        jLabel13 = new javax.swing.JLabel();
        panelRound8 = new lib.PanelRound();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panelRound10 = new lib.PanelRound();
        jLabel17 = new javax.swing.JLabel();
        panelRound11 = new lib.PanelRound();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelCircleImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/LibaryImages/ProfileImages/pexels-matheus-bertelli-1906157.jpg"))); // NOI18N
        jPanel1.add(rSPanelCircleImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 280, 280));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibaryImages/ProfileImages/pexels-pixabay-261821.jpg"))); // NOI18N
        jPanel1.add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 410));

        jLabel1.setFont(new java.awt.Font("Calibri Light", 3, 36)); // NOI18N
        jLabel1.setText(" Mathuse hartz");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 280, 90));

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        jLabel2.setText("Love reading books");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        jLabel3.setText("hiking in the woods");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 620, -1, -1));

        jLabel22.setFont(new java.awt.Font("Glass Antiqua", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Books Read");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 490, -1, -1));

        jPanel12.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(153, 153, 255)));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_bookcount.setFont(new java.awt.Font("Glass Antiqua", 1, 50)); // NOI18N
        txt_bookcount.setForeground(new java.awt.Color(102, 102, 102));
        txt_bookcount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_Shelf_50px.png"))); // NOI18N
        txt_bookcount.setText("7");
        jPanel12.add(txt_bookcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 750, 220, 130));

        jLabel23.setFont(new java.awt.Font("Glass Antiqua", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Currently Borrowed");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 700, -1, -1));

        jPanel14.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(153, 153, 255)));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_bookcount2.setFont(new java.awt.Font("Glass Antiqua", 1, 50)); // NOI18N
        txt_bookcount2.setForeground(new java.awt.Color(102, 102, 102));
        txt_bookcount2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_Shelf_50px.png"))); // NOI18N
        txt_bookcount2.setText("178");
        jPanel14.add(txt_bookcount2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 530, 220, 130));

        jPanel13.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(153, 153, 255)));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_bookcount1.setFont(new java.awt.Font("Glass Antiqua", 1, 50)); // NOI18N
        txt_bookcount1.setForeground(new java.awt.Color(102, 102, 102));
        txt_bookcount1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_Shelf_50px.png"))); // NOI18N
        txt_bookcount1.setText("54");
        jPanel13.add(txt_bookcount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 970, 220, 130));

        jLabel24.setFont(new java.awt.Font("Glass Antiqua", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("On Wishlist");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 920, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 26)); // NOI18N
        jLabel6.setText("Currently Reading: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1150, -1, -1));

        panelRound1.setRoundBottomLeft(40);
        panelRound1.setRoundBottomRight(40);
        panelRound1.setRoundTopLeft(40);
        panelRound1.setRoundTopRight(40);

        jLabel5.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel5.setText("FICTION");
        panelRound1.add(jLabel5);

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 770, 160, 50));

        panelRound2.setRoundBottomLeft(40);
        panelRound2.setRoundBottomRight(40);
        panelRound2.setRoundTopLeft(40);
        panelRound2.setRoundTopRight(40);

        jLabel7.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel7.setText("THRILLER");
        panelRound2.add(jLabel7);

        jPanel1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 770, 160, 50));

        panelRound3.setRoundBottomLeft(40);
        panelRound3.setRoundBottomRight(40);
        panelRound3.setRoundTopLeft(40);
        panelRound3.setRoundTopRight(40);

        jLabel8.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel8.setText("HISTORY");
        panelRound3.add(jLabel8);

        jPanel1.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 770, 160, 50));

        panelRound4.setRoundBottomLeft(40);
        panelRound4.setRoundBottomRight(40);
        panelRound4.setRoundTopLeft(40);
        panelRound4.setRoundTopRight(40);

        jLabel9.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel9.setText("NOVEL");
        panelRound4.add(jLabel9);

        jPanel1.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 770, 160, 50));

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 26)); // NOI18N
        jLabel10.setText("Favorite Genre: ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, -1, -1));

        panelRound5.setBackground(new java.awt.Color(153, 153, 255));
        panelRound5.setRoundBottomLeft(40);
        panelRound5.setRoundBottomRight(40);
        panelRound5.setRoundTopLeft(40);
        panelRound5.setRoundTopRight(40);

        jLabel11.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("THE ALCHEMIST");
        panelRound5.add(jLabel11);

        jPanel1.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 1030, 380, 50));

        panelRound6.setBackground(new java.awt.Color(153, 153, 255));
        panelRound6.setRoundBottomLeft(40);
        panelRound6.setRoundBottomRight(40);
        panelRound6.setRoundTopLeft(40);
        panelRound6.setRoundTopRight(40);

        jLabel12.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("THE KITE RUNNER");
        panelRound6.add(jLabel12);

        jPanel1.add(panelRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 940, 380, 50));

        panelRound7.setBackground(new java.awt.Color(153, 153, 255));
        panelRound7.setRoundBottomLeft(40);
        panelRound7.setRoundBottomRight(40);
        panelRound7.setRoundTopLeft(40);
        panelRound7.setRoundTopRight(40);

        jLabel13.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("SHOE DOG");
        panelRound7.add(jLabel13);

        jPanel1.add(panelRound7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 940, 380, 50));

        panelRound8.setBackground(new java.awt.Color(153, 153, 255));
        panelRound8.setRoundBottomLeft(40);
        panelRound8.setRoundBottomRight(40);
        panelRound8.setRoundTopLeft(40);
        panelRound8.setRoundTopRight(40);

        jLabel14.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("MORNING IN THE JENIN");
        panelRound8.add(jLabel14);

        jPanel1.add(panelRound8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1030, 380, 50));

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 26)); // NOI18N
        jLabel15.setText("Favorite Books: ");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 870, -1, -1));

        panelRound10.setBackground(new java.awt.Color(153, 204, 255));
        panelRound10.setRoundBottomLeft(40);
        panelRound10.setRoundBottomRight(40);
        panelRound10.setRoundTopLeft(40);
        panelRound10.setRoundTopRight(40);

        jLabel17.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("WHERE THE SIDWALK ENDS");
        panelRound10.add(jLabel17);

        jPanel1.add(panelRound10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1240, 380, 50));

        panelRound11.setBackground(new java.awt.Color(153, 204, 255));
        panelRound11.setRoundBottomLeft(40);
        panelRound11.setRoundBottomRight(40);
        panelRound11.setRoundTopLeft(40);
        panelRound11.setRoundTopRight(40);

        jLabel18.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("HOME BODY");
        panelRound11.add(jLabel18);

        jPanel1.add(panelRound11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 1240, 380, 50));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1360, 1220, 10));

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 750));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private lib.PanelRound panelRound1;
    private lib.PanelRound panelRound10;
    private lib.PanelRound panelRound11;
    private lib.PanelRound panelRound2;
    private lib.PanelRound panelRound3;
    private lib.PanelRound panelRound4;
    private lib.PanelRound panelRound5;
    private lib.PanelRound panelRound6;
    private lib.PanelRound panelRound7;
    private lib.PanelRound panelRound8;
    private rojerusan.RSLabelImage rSLabelImage1;
    private rojerusan.RSPanelCircleImage rSPanelCircleImage1;
    private javax.swing.JLabel txt_bookcount;
    private javax.swing.JLabel txt_bookcount1;
    private javax.swing.JLabel txt_bookcount2;
    // End of variables declaration//GEN-END:variables
}
