/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package booksh;

import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JScrollBar;

/**
 *
 * @author shadman
 */
public class UserIssuedBooks extends javax.swing.JPanel {

    /**
     * Creates new form UserProfile
     */
    public UserIssuedBooks() {
        initComponents();
        update_list();
        JScrollBar verticalScrollBar = ScrollView.getVerticalScrollBar();
        verticalScrollBar.setUnitIncrement(20);
        verticalScrollBar.setBlockIncrement(200);
    }

    BookView booklist = null;

    public void update_list() {
        var books = new ArrayList<Book>();

        try {
            Connection con = DBConnection.getConnection();
            String query = "SELECT * FROM borrowed_books INNER JOIN book_details ON book_details.book_id = borrowed_books.book_id WHERE user_id = ?";
            var st = con.prepareStatement(query);
            st.setInt(1, Globals.user);

            var rs = st.executeQuery();
            while (rs.next()) {
                books.add(new Book(rs));
            }
            update_res_panel(new BookView(books));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void update_res_panel(BookView bv) {
        if (booklist != null) ScrollView.getViewport().remove(booklist);
        ScrollView.getViewport().add(bv);
        this.validate();
        this.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        ScrollView = new javax.swing.JScrollPane();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Glass Antiqua", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(251, 51, 51));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Book_50px_1.png"))); // NOI18N
        jLabel11.setText("Borrowed");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 210, 90));

        ScrollView.setBorder(null);
        add(ScrollView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1220, 630));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollView;
    private javax.swing.JLabel jLabel11;
    // End of variables declaration//GEN-END:variables
}
