/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package booksh;

/**
 *
 * @author shadman
 */
public class ViewRecords extends javax.swing.JPanel {

    /**
     * Creates new form ManageBooksPanel
     */
    public ViewRecords() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_booklist = new rojerusan.RSTableMetro();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_booklist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"20/02/23", "Borrow", "user1", "user borrowd book by auth9or"},
                {"12/03/22", "buy", "user2", "user2 bought by author"}
            },
            new String [] {
                "Date", "Book", "User", "description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_booklist.setColorBackgoundHead(new java.awt.Color(51, 102, 255));
        tbl_booklist.setColorBordeFilas(new java.awt.Color(51, 102, 255));
        tbl_booklist.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbl_booklist.setColorFilasForeground1(new java.awt.Color(102, 102, 102));
        tbl_booklist.setColorFilasForeground2(new java.awt.Color(102, 102, 102));
        tbl_booklist.setColorSelBackgound(new java.awt.Color(102, 102, 102));
        tbl_booklist.setFont(new java.awt.Font("Glass Antiqua", 0, 25)); // NOI18N
        tbl_booklist.setFuenteFilas(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl_booklist.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        tbl_booklist.setFuenteHead(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        tbl_booklist.setRowHeight(40);
        jScrollPane2.setViewportView(tbl_booklist);
        if (tbl_booklist.getColumnModel().getColumnCount() > 0) {
            tbl_booklist.getColumnModel().getColumn(3).setMinWidth(600);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1210, 640));

        jLabel11.setFont(new java.awt.Font("Glass Antiqua", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(251, 51, 51));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Book_50px_1.png"))); // NOI18N
        jLabel11.setText("Records");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 190, 90));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane2;
    private rojerusan.RSTableMetro tbl_booklist;
    // End of variables declaration//GEN-END:variables
}
